### ISSUE TITLE
Only use one image tag per shop item

### ISSUE THREAD

**Issue by acacheung** [andrealeigh/dobot#15]
Currently mobile and desktop images are getting a display block or none when one should be hidden. This is the easiest way to complete this task, but harder to maintain because devs would need to update the image in multiple places. Try floating the image when it gets to a desktop view.

**Comment by andrealeigh** [comment]
Hey. I'm having a lot of trouble with this issue, would you mind looking at my restructure-to-1-column branch? IDK if I'm on the right track. Thanks

**Comment by andrealeigh** [comment]
Ok, I think I did it! Take a look, let me know what you think.
