### ISSUE TITLE
Image too big on larger screen widths

### ISSUE THREAD

**Issue by acacheung** [andrealeigh/dobot#8]
![screen shot 2015-03-01 at 3 15 41 pm](https://cloud.githubusercontent.com/assets/1054686/6432632/d972c554-c025-11e4-9c55-be7aa4e3a1da.png)

I'd like negative space on both sides and the content to max out at 940px

**Comment by andrealeigh** [comment]
Hey Amanda! 

I added larger left/right margins to the section, but not in between the two columns (the width between description column and image is still the same). Also added { max-width: 940px; } to both columns. 

Is this was not what you were looking for let me know! I will keep this issue open for now.
